# -*- coding: utf-8 -*-
"""SK_Hello_World.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kIa72S2eOVbjbxPvCn9A9QKQg_wuq9QO
"""

import streamlit

streamlit.title('hello world')

streamlit.header('header')
streamlit.text('text')